### ISSUE TITLE
Address Blacklight 8 deprecation warnings

### ISSUE THREAD

**Issue by cbeer** [projectblacklight/arclight#1056]
- [x] #1063 DEPRECATION WARNING: Initializing a Blacklight::Configuration::ViewConfig implicitly (by calling online_contents) is deprecated. Call it as online_contents! or pass initialize arguments. 
       DEPRECATION WARNING: Initializing a Blacklight::Configuration::ViewConfig implicitly (by calling collection_context) is deprecated
       DEPRECATION WARNING: Initializing a Blacklight::Configuration::ViewConfig implicitly (by calling compact) is deprecated. Call it as compact! or pass initialize arguments.

- [x] #1053 DEPRECATION WARNING: facet_limit_for is deprecated and will be removed from a future release (moving to private logic in Blacklight::FacetFieldPresenter).

- [x] DEPRECATION WARNING: document_has_value? is deprecated and will be removed in Blacklight 8. Use DocumentPresenter#has_value? instead. (called from block (2 levels) in <module:ArclightHelper> at /app/helpers/arclight_helper.rb:251) (912 times)
- [x] DEPRECATION WARNING: #show_presenter is deprecated; use #document_presenter instead. (called at app/views/catalog/_custom_metadata.html.erb:1) (122 times)
       DEPRECATION WARNING: #show_presenter is deprecated; use #document_presenter instead. (called at app/views/catalog/_access_contents.html.erb:1)

- [ ] DEPRECATION WARNING: render_search_bar is deprecated and will be removed from a future release (Call `render Blacklight::SearchBarComponent.new' instead). 
       DEPRECATION WARNING: search_bar_presenter is deprecated and will be removed from a future release. 
       DEPRECATION WARNING: render is deprecated and will be removed from a future release (The SearchBarPresenter has been deprecated. Call `render Blacklight::SearchBarComponent.new' instead).

- [x] #1055 DEPRECATION WARNING: render_hash_as_hidden_fields is deprecated and will be removed from a future release (Use Blacklight::HiddenSearchStateComponent instead).
        DEPRECATION WARNING: search_fields is deprecated and will be removed from a future release (removed without replacement). 
        DEPRECATION WARNING: search_field_options_for_select is deprecated and will be removed from a future release (removed without replacement).

- [x] DEPRECATION WARNING: Blacklight 8 will filter out non-search parameter, including: hierarchy_context and original_document. (called from permit_search_params)
       DEPRECATION WARNING: Blacklight 8 will filter out non-search parameter, including: group.

- [x] DEPRECATION WARNING: render_opensearch_response_metadata is deprecated and will be removed from a future release (Use `render "catalog/opensearch_response_metadata"' instead). 

- [x] #1094 DEPRECATION WARNING: Calling render_document_index without documents is deprecated and will be removed in version 8. (called at app/views/catalog/_search_results.html.erb:25) (149 times)

- [x] #1062 DEPRECATION WARNING: document_show_link_field is deprecated and will be removed from a future release (Deprecated without replacement). 
      DEPRECATION WARNING: passing a Symbol to link_to_document is deprecated and will be removed in Blacklight 8. (called at app/views/catalog/_index_collection_context_default.html.erb:24) (1700 times)
      DEPRECATION WARNING: #index_presenter is deprecated; use #document_presenter instead. (called from block in link_to_document)

- [x] #1066 DEPRECATION WARNING: #show_presenter is deprecated; use #document_presenter instead. (called from block at app/views/catalog/_show_upper_metadata_default.html.erb:5)

- [x] DEPRECATION WARNING: render_grouped_document_index is deprecated and will be removed from a future release (Removed without replacement). (called at app/views/catalog/_search_results.html.erb:23) (6 times);

- [ ] DEPRECATION WARNING: facet_params is deprecated and will be removed from blacklight 8.0. (called from repository_faceted_on at app/helpers/arclight_helper.rb:172) (2 times)
- [x]  #1054 DEPRECATION WARNING: render_hash_as_hidden_fields is deprecated and will be removed from a future release (Use Blacklight::HiddenSearchStateComponent instead).
