### ISSUE TITLE
Viewer for digital objects - oEmbed

### ISSUE THREAD

**Issue by anarchivist** [projectblacklight/arclight#242]
This is intended to add a viewer for digital objects that are associated with a collection or component.

The presumption for _this ticket_ is that digital objects will have an oEmbed service associated with them; however, in a broader sense, ArcLight may not want to constrain this too tightly (e.g., we may want to be able to incorporate IIIF image/prezi resources later). 

**Acceptance criteria**

* [x] Determine whether a digital object has an oEmbed endpoint associated with it #276 
* [x] If a component has oEmbed data associated with it:
    * [x] Display an embedded viewer on the _component detail page_ #278 
    * [x] Display a link to the digital object #237 
* [x] If a collection has oEmbed data associated with it:
    * [x] Display an embedded viewer on the _collection detail page_ #277 
    * [x] Display a link to the digital object as in #237 
* [x] If an object is not embeddable:
    * [x] Display a link to the digital object #237 

**Mockup**

![arclight-mockups-mvp](https://cloud.githubusercontent.com/assets/73732/25765456/0d2e1fb6-31a2-11e7-8740-c216da9512a9.jpg)

**Comment by sdellis** [comment]
👍 to oEmbed alternatives (i.e., using IIIF image/prezi resources directly).  How many institutions besides Stanford have an oEmbed service in place?

**Comment by anarchivist** [comment]
@sdellis The pull request that implements this (#317) also provides a Viewer class that can be configured. We may try to implement another Viewer class depending on time but this should be straightforward enough from a development perspective to extend.

**Comment by jkeck** [comment]
Also, I have it on my to-do list to write up a page in our wiki to give a simple walk-through of how an application would provide their own custom viewer logic.

**Comment by escowles** [comment]
One related issue is how tightly coupled, and what the direction of integration is between ArcLight and digital objects.  Princeton has two different approaches (sometimes existing in the same application):

1. The digital repository pushes a link to the data (in this case EAD) and that eventually gets reindexed and the digital content displays.  The advantage of this approach is having an official record of the digital object linkage — but the downside is that it often takes a long time for this to happen.

2. The discovery system queries the repository for digital objects related to the record (in this case we use an EAD component ID), and displays any objects found.  The advantage is that the objects display much more quickly, but there is no record of the linkage.

These two scenarios often co-exist, either for different subsets of data, or even the same object (using approach #2 to display objects quickly, but approach #1 to eventually record the linkage).

Related to #89 and #61, in that indexing the linkage would allow using the digital object for a thumbnail, but the display-time query might not be practical.

**Comment by thatbudakguy** [comment]
closing this ticket since all sub-tasks are done.
