### ISSUE TITLE
Analyze and improve relevance ranking

### ISSUE THREAD

**Issue by anarchivist** [projectblacklight/arclight#532]
Users regularly report that they don't know why certain results are being shown first 

* [x] Document factors leading to search relevance #597 
* [ ] Relevance: adjust boost on titles for components/collections #723
* [ ] Relevance: provide documentation on Solr configuration (especially boost/query analysis) #724
* [x] Relevance: analyze stemming behavior #725
* [x] Better support known-item searching for collections #726
* [ ] Relevance behavior grouped results #727

**Comment by mejackreed** [comment]
Related to #531

**Comment by seanaery** [comment]
Closing out this ticket as we have implemented several relevance improvements in the [Dec 2023 community sprint](https://github.com/orgs/projectblacklight/projects/3/views/2). We have also updated the wiki doc here: https://github.com/projectblacklight/arclight/wiki/Configuring-Solr-and-Search-Relevancy
