### ISSUE TITLE
Update page header area for component show pages

### ISSUE THREAD

**Issue by ggeisler** [projectblacklight/arclight#628]
This is a story ticket with several specific work tickets that involve updates to how we display information in the component show page headers (collection detail page and component detail pages on down the hierarchy from the collection):

<img width="1245" alt="Screen Shot 2019-08-26 at 10 51 09 AM" src="https://user-images.githubusercontent.com/101482/63711425-40844700-c7f0-11e9-83fe-d3c00d92dd18.png">

- [x] #629 - A: Update breadcrumbs to remove current page from hierarchy
- [x] #630 - B: Adjust placement of component page title and component metadata
- [x] #631 - C: Add component context/actions box to component show page
- [ ] #637 - Ensure component title wraps appropriately
- [x] #640 - Add download links to component context/actions box when appropriate

**Comment by mejackreed** [comment]
Closing this epic. Most of the items have been completed. The remaining piece is ticketed, but likely difficult to implement.
