### ISSUE TITLE
Revise tab/panel layout on component show pages

### ISSUE THREAD

**Issue by jvine** [projectblacklight/arclight#632]
Story ticket to reorganize the content section of the collection and component pages, to make better use of space and deprecate static content. 

- [x] A #633: Create an Access tab as the last tab.
- [x] B #633: Move the content of the accordion section (In person, Terms, How to cite) of the sidebar into the Access tab.
- [x] C #638: Move the Navigation overview section into the Overview tab.
- [x] D #639: Remove the Search within this collection box.
_(Tasks B, C, and D together completely remove the sticky sidebar section from the page.)_
- [x] E #645: Make the tab section use the full 12 columns. 

### Before
<img width="1133" alt="Tabs before" src="https://user-images.githubusercontent.com/6945691/63717217-8e06b100-c7fc-11e9-87d0-2561268b54be.png">

### After (Overview tab)
<img width="1010" alt="Tabs after" src="https://user-images.githubusercontent.com/6945691/63717232-95c65580-c7fc-11e9-8c7f-b1ca2f24ecc0.png">

### After (Access tab)
<img width="1000" alt="Tabs after 2" src="https://user-images.githubusercontent.com/6945691/63717430-0c635300-c7fd-11e9-9727-85e274f18549.png">
