### ISSUE TITLE
Generate a request submitted to Aeon's external request endpoint (single items)

### ISSUE THREAD

**Issue by anarchivist** [projectblacklight/arclight#650]
**Acceptance criteria**

Given a repository with a properly configured Aeon instance (see #641 and #647), I should be able to generate a single-item request for a given component using the request button. Clicking the form should pass information off to Aeon's [external request endpoint](https://support.atlas-sys.com/hc/en-us/articles/360011820054-External-Request-Endpoint) where a user can login and complete the request.

* [ ] Implement mapping configuration in #647, supporting both accessors and static values
* [ ] For multivalued fields, join values with `"; "` and return a string
* [ ] Generate the necessary form elements described in the [Aeon docs](https://support.atlas-sys.com/hc/en-us/articles/360011820054-External-Request-Endpoint) and in [@sdellis's comment](https://github.com/projectblacklight/arclight/issues/650#issuecomment-526307924) from mappings set in configuration
* [ ] Clicking the request button should send the request to the Aeon instance via a `POST` request to `$aeon_web_url/aeon.dll?Action=11&Type=200`

**Out of scope**

* Logic to determine what's requestable (see #728)
* Handling multiple items per request (see #729) 

<details><summary>Example</summary>
If I define a configuration as follows (mockup only):

```yaml
request_type: aeon_external_request_endpoint
aeon_external_request_endpoint:
  aeon_web_url: https://example.com/aeon/aeon.dll
  aeon_ere_mapping:
    SystemId: "ArcLight" # static value
    ItemTitle: collection_title # this is an accessor
    ItemSubTitle: component_title # this is an accessor
    ItemVolume: component_box # accessor
    ItemInfo1: "manuscript" # this is a static value
```

And assuming the following:

```json
{
  "collection_title": "Letters of Thomas Jefferson",
  "component_title": "1789 ALS",
  "component_box": "Box 1"
}
```

I should see a form like the following:

```html
<form action="http://example.com/aeon/aeon.dll?Action=11&Type=200" method="post">
	<input type="hidden" name="SystemID" value="ArcLight">
	<input type="hidden" name="ItemTitle" value="Letters of Thomas Jefferson">
	<input type="hidden" name="ItemSubtitle" value="1789 ALS">
	<input type="hidden" name="ItemVolume" value="Box 1">
	<input type="hidden" name="ItemInfo1" value="manuscript">
	<input type="submit" value="Request">
</form>
```
</details>

<details><summary>TO DETERMINE (completed)</summary>

* [x] Do we need to do anything specific to associate the request with that specific component? 
* [x] What is the correct URL to send a POST request to?
* [x] What information other than what's listed in #647 needs to be sent as part of the request? (Examples: date of visit, notes/comments, Aeon request grouping configuration? Or can these be handled downstream by Aeon?)
</details>

**Comment by eckardm** [comment]
Hi Mark, is this helpful? view-source:https://quod.lib.umich.edu/f/findaid/aeonform.js

I found that by looking to see what happens when you hit our request button:

![image](https://user-images.githubusercontent.com/7072443/63963633-75e49b00-ca63-11e9-8361-9e98abc6d457.png)

Looking at that (as a layperson), it looks like after the `SubmitAeonRequestForm()` button is selected (which also checks to makes sure something's been selected to be requested),  a new confirmation screen comes up with some information preloaded, e.g.:

![image](https://user-images.githubusercontent.com/7072443/63964740-be9d5380-ca65-11e9-919d-7f6987a3a1f4.png)

Before the `SubmitAeonConfirmForm()` button can be run, we prompt users for a date. And there are prompts for "Special Requests/Questions?" (for library staff) and "Notes" (for personal reference, visible to library staff, but do not receive staff attention). Maybe that's useful for your third bullet?

In case it helps answer some of your questions about what's expected/required, I'm also sending you a Bentley Aeon Field Mapping document we created going on 5 years ago that discusses a subset of what's in #647 . From that, it looks like `ItemTitle`, `CallNumber` and `ScheduledDate` are required, and that `ItemSubTitle`, `ItemAuthor`, `ItemPlace`, `ItemPublisher`, `ItemDate`, `ItemVolume`, `ItemInfo1` (restrictions) are present, and some are just hidden: `ReferenceNumber`, `ItemNumber` and `SubLocation`. I'm not sure which of those are just for the forms though and which actually get passed to Aeon.

Finally, one of my colleagues suggested that folks from Aeon might be willing to help out with this. I'll follow-up about this via email as well.

**Comment by sdellis** [comment]
The `aeon.xslt` (transforms your EAD into an internal Aeon html representation) and `EADrequest.js` (basic validation and helpers) _are not necessary for the External Method_, as it's on you to provide the equivalent functionality. 

# Princeton Example
At the bottom of this comment is a form that is used to request three components, which are contained in two boxes (Box 1 and Box 5). You can see that the form is submitted to the Aeon.dll, but this is done via JavaScript since only the inputs contained in the `<label>` elements (not the `<li>` elements) get sent to Aeon. 

The inputs contained in the `<li>` elements are what the user sees (see the screenshot). 

![Screen Shot 2019-08-29 at 2 09 54 PM](https://user-images.githubusercontent.com/609368/63966547-839d1f00-ca69-11e9-8fa9-593a45010677.png)

Since the user requested three components in this example, but Aeon only deals with containers, any components that are in the same container (or inversely, any components that are comprised of multiple containers) must be transformed into a grouped request item for each container before being sent to Aeon. If at this confirmation screen, a user un-checks one of the components, the JavaScript rewrites the inputs that get sent to Aeon.

These containers are grouped by a unique id, which is used as a suffix, separated by an underscore, for each field related to that request. For example, the id `barcode-32101038559975` is added to the `name` attribute of it's author like this: `name="ItemAuthor_barcode-32101038559975"`

Finally, the ItemInfo fields (1-5) can be mapped to any value in Aeon. These generally are optional, but for example, ItemInfo1 is currently mapped to the `<accessrestrict>` note which tells Public Services staff whether or not the patron is allowed to see the materials, which saves time and prevents mistakes. ItemInfo3 is mapped to the subcontainers (i.e., folders), and so on.

```
<form id="request-confirm" method="post" action="https://lib-aeon.princeton.edu/aeon/Aeon.dll">            
<ul class="inputs-list">
  <label for="barcode-32101038559975">
    <input type="hidden" class="request-check" name="Request" value="barcode-32101038559975">
    <input type="hidden" class="barcode-32101038559975" name="ItemSubTitle_barcode-32101038559975" value="The King's Quair">
    <input type="hidden" class="barcode-32101038559975" name="ItemTitle_barcode-32101038559975" value="William E. Fredeman Collection of William Bell Scott, the Scott Family, and Alice Boyd">
    <input type="hidden" class="barcode-32101038559975" name="ItemAuthor_barcode-32101038559975" value="Fredeman, William E. (William Evan), 1928-">
    <input type="hidden" class="barcode-32101038559975" name="ItemDate_barcode-32101038559975" value="1887">
    <input type="hidden" class="barcode-32101038559975" name="ReferenceNumber_barcode-32101038559975" value="C1459_c27">
    <input type="hidden" class="barcode-32101038559975" name="CallNumber_barcode-32101038559975" value="C1459">
    <input type="hidden" class="barcode-32101038559975" name="ItemNumber_barcode-32101038559975" value="Barcode: 32101038559975">
    <input type="hidden" class="barcode-32101038559975" name="ItemVolume_barcode-32101038559975" value="Box 5">
    <input type="hidden" class="barcode-32101038559975" name="Location_barcode-32101038559975" value="Mss">
    <input type="hidden" class="barcode-32101038559975" name="ItemInfo1_barcode-32101038559975" value="Collection is open for research use.">
    <input type="hidden" class="barcode-32101038559975" name="ItemInfo2_barcode-32101038559975" value="4.0 linear feet | 6 boxes">
    <input type="hidden" class="barcode-32101038559975" name="ItemInfo3_barcode-32101038559975" value="">
    <input type="hidden" class="barcode-32101038559975" name="ItemInfo4_barcode-32101038559975" value="P,">
    <input type="hidden" class="barcode-32101038559975" name="ItemInfo5_barcode-32101038559975" value="https://findingaids.princeton.edu/collections/C1459/c24">
  </label>
  <label for="32101038559934">
    <input type="hidden" class="request-check" name="Request" value="32101038559934">
    <input type="hidden" class="32101038559934" name="ItemSubTitle_32101038559934" value="The King's Quair">
    <input type="hidden" class="32101038559934" name="ItemTitle_32101038559934" value="William E. Fredeman Collection of William Bell Scott, the Scott Family, and Alice Boyd">
    <input type="hidden" class="32101038559934" name="ItemAuthor_32101038559934" value="Fredeman, William E. (William Evan), 1928-">
    <input type="hidden" class="32101038559934" name="ItemDate_32101038559934" value="1872 October 13-1885 October 16">
    <input type="hidden" class="32101038559934" name="ReferenceNumber_32101038559934" value="C1459_c25,C1459_c26">
    <input type="hidden" class="32101038559934" name="CallNumber_32101038559934" value="C1459">
    <input type="hidden" class="32101038559934" name="ItemNumber_32101038559934" value="32101038559934">
    <input type="hidden" class="32101038559934" name="ItemVolume_32101038559934" value="Box1">
    <input type="hidden" class="32101038559934" name="Location_32101038559934" value="mss">
    <input type="hidden" class="32101038559934" name="ItemInfo1_32101038559934" value="Collection is open for research use.">
    <input type="hidden" class="32101038559934" name="ItemInfo2_32101038559934" value="4.0 linear feet | 6 boxes">
    <input type="hidden" class="32101038559934" name="ItemInfo3_32101038559934" value=" 18, 19">
    <input type="hidden" class="32101038559934" name="ItemInfo4_32101038559934" value="">
    <input type="hidden" class="32101038559934" name="ItemInfo5_32101038559934" value="https://findingaids.princeton.edu/collections/C1459/c24">
  </label>
  
  <li class="d342437e68a1310">
    <label for="Request_d342437e68a1310">
      <input type="checkbox" class="request-check" name="Request" value="d342437e68a1310" id="Request_d342437e68a1310">
      <input type="hidden" class="d342437e77" name="ItemSubTitle_d342437e68a1310" value="&quot;The King's Quair&quot; at Penkill Castle / Drawings for Penkill Castle">
      <input type="hidden" class="d342437e77" name="ItemTitle_d342437e68a1310" value="William E. Fredeman Collection of William Bell Scott, the Scott Family, and Alice Boyd">
      <input type="hidden" class="d342437e77" name="ItemAuthor_d342437e68a1310" value="Fredeman, William E. (William Evan), 1928-">
      <input type="hidden" class="d342437e77" name="ItemDate_d342437e68a1310" value="1872 October 13-1885 October 16">
      <input type="hidden" class="d342437e77" name="ReferenceNumber_d342437e68a1310" value="C1459_c25">
      <input type="hidden" class="d342437e77" name="CallNumber_d342437e68a1310" value="C1459">
      <input type="hidden" class="d342437e68a1310" name="ItemNumber_d342437e68a1310" value="32101038559934,">
      <input type="hidden" class="d342437e68a1310" name="ItemVolume_d342437e68a1310" value="Box1,">
      <input type="hidden" class="d342437e68a1310" name="ItemInfo1_d342437e68a1310" value="Collection is open for research use.">
      <input type="hidden" class="d342437e68a1310" name="ItemInfo2_d342437e68a1310" value="4.0 linear feet | 6 boxes">
      <input type="hidden" class="d342437e68a1310" name="ItemInfo3_d342437e68a1310" value="Folder 18">
      <input type="hidden" class="d342437e68a1310" name="ItemInfo4_d342437e68a1310" value=",">
      <input type="hidden" class="d342437e68a1310" name="Location_d342437e68a1310" value="mss,">
      <input type="hidden" class="d342437e68a1310" name="ItemInfo5_d342437e68a1310" value="https://findingaids.princeton.edu/collections/C1459/c24">
      <span> "The King's Quair" at Penkill Castle / Drawings for Penkill Castle</span>
    </label>
    <span style="margin-left:20px">Call Number: C1459</span><br>
    <span style="margin-left:20px">Container: Box1, Folder 18</span>
  </li>
  <li class="d342437e87a1310">
    <label for="Request_d342437e87a1310">
      <input type="checkbox" class="request-check" name="Request" value="d342437e87a1310" id="Request_d342437e87a1310">
      <input type="hidden" class="d342437e96" name="ItemSubTitle_d342437e87a1310" value="&quot;The King's Quair&quot; at Penkill Castle / Mock-up Title Page for The Illustrations to the King's Quair at Penkill Castle, Painted and Etched by William Bell Scott">
      <input type="hidden" class="d342437e96" name="ItemTitle_d342437e87a1310" value="William E. Fredeman Collection of William Bell Scott, the Scott Family, and Alice Boyd">
      <input type="hidden" class="d342437e96" name="ItemAuthor_d342437e87a1310" value="Fredeman, William E. (William Evan), 1928-">
      <input type="hidden" class="d342437e96" name="ItemDate_d342437e87a1310" value="circa 1887">
      <input type="hidden" class="d342437e96" name="ReferenceNumber_d342437e87a1310" value="C1459_c26">
      <input type="hidden" class="d342437e96" name="CallNumber_d342437e87a1310" value="C1459">
      <input type="hidden" class="d342437e87a1310" name="ItemNumber_d342437e87a1310" value="32101038559934,">
      <input type="hidden" class="d342437e87a1310" name="ItemVolume_d342437e87a1310" value="Box1,">
      <input type="hidden" class="d342437e87a1310" name="ItemInfo1_d342437e87a1310" value="Collection is open for research use.">
      <input type="hidden" class="d342437e87a1310" name="ItemInfo2_d342437e87a1310" value="4.0 linear feet | 6 boxes">
      <input type="hidden" class="d342437e87a1310" name="ItemInfo3_d342437e87a1310" value="Folder 19">
      <input type="hidden" class="d342437e87a1310" name="ItemInfo4_d342437e87a1310" value=",">
      <input type="hidden" class="d342437e87a1310" name="Location_d342437e87a1310" value="mss,">
      <input type="hidden" class="d342437e87a1310" name="ItemInfo5_d342437e87a1310" value="https://findingaids.princeton.edu/collections/C1459/c24">
      
      <span> "The King's Quair" at Penkill Castle / Mock-up Title Page for The Illustrations to the King's Quair at Penkill Castle, Painted and Etched by William Bell Scott</span>
    </label>
    <span style="margin-left:20px">Call Number: C1459</span><br>
    <span style="margin-left:20px">Container: Box1, Folder 19</span></li>
  <li class="d342437e105a1310">
    <label for="Request_d342437e105a1310">
      <input type="checkbox" class="request-check" name="Request" value="d342437e105a1310" id="Request_d342437e105a1310">
      <input type="hidden" class="d342437e114" name="ItemSubTitle_d342437e105a1310" value="&quot;The King's Quair&quot; at Penkill Castle / Illustrations to the King's Quair of King James I. of Scotland Painted on the Staircase of Penkill Castle, Ayrshire">
      <input type="hidden" class="d342437e114" name="ItemTitle_d342437e105a1310" value="William E. Fredeman Collection of William Bell Scott, the Scott Family, and Alice Boyd">
      <input type="hidden" class="d342437e114" name="ItemAuthor_d342437e105a1310" value="Fredeman, William E. (William Evan), 1928-">
      <input type="hidden" class="d342437e114" name="ItemDate_d342437e105a1310" value="1887">
      <input type="hidden" class="d342437e114" name="ReferenceNumber_d342437e105a1310" value="C1459_c27">
      <input type="hidden" class="d342437e114" name="CallNumber_d342437e105a1310" value="C1459">
      <input type="hidden" class="d342437e105a1310" name="ItemNumber_d342437e105a1310" value="Barcode: 32101038559975,">
      <input type="hidden" class="d342437e105a1310" name="ItemVolume_d342437e105a1310" value="Box 5,">
      <input type="hidden" class="d342437e105a1310" name="ItemInfo1_d342437e105a1310" value="Collection is open for research use.">
      <input type="hidden" class="d342437e105a1310" name="ItemInfo2_d342437e105a1310" value="4.0 linear feet | 6 boxes">
      <input type="hidden" class="d342437e105a1310" name="ItemInfo3_d342437e105a1310" value="">
      <input type="hidden" class="d342437e105a1310" name="ItemInfo4_d342437e105a1310" value="P,">
      <input type="hidden" class="d342437e105a1310" name="Location_d342437e105a1310" value="Mss,">
      <input type="hidden" class="d342437e105a1310" name="ItemInfo5_d342437e105a1310" value="https://findingaids.princeton.edu/collections/C1459/c24">
      <span> "The King's Quair" at Penkill Castle / Illustrations to the King's Quair of King James I. of Scotland Painted on the Staircase of Penkill Castle, Ayrshire</span>
    </label>
    <span style="margin-left:20px">Call Number: C1459</span><br>
    <span style="margin-left:20px">Container: Box 5 </span>
  </li>
</ul>
</form>
```

**Comment by anarchivist** [comment]
Thanks @sdellis and @eckardm - I think this is probably enough to get started. I may need each of you to take a look at this ticket again once I revise it to be actionable to make sure I've characterized it correctly.

**Comment by anarchivist** [comment]
@sdellis @eckardm @cmkpowell - any feedback here is welcome; @mejackreed have fleshed out the ticket and think it's now actionable.
