### ISSUE TITLE
Update display of search results

### ISSUE THREAD

**Issue by ggeisler** [projectblacklight/arclight#667]
This is a story ticket covering several more specific work tickets:

- [x] #669 - Update list view of search results
- [x] #671 - Update compact view of search results
- [x] #706 - Group results by collection toggle
- [x] #676 - Add sort option to group search results by collection
- [x] #681 (epic) - Add a list view for grouped search results
- [x] #682 - Add a compact view for grouped search results

**Comment by mejackreed** [comment]
Closing this epic as I think the straggling issues are now 🚢
