### ISSUE TITLE
Update/add collection contents navigation on show pages

### ISSUE THREAD

**Issue by jvine** [projectblacklight/arclight#668]
Currently:
1. Collection show page has a "Contents" tab that displays the complete collection tree
2. all other component show pages have a static snapshot of the context around the current component.

Revised design involves several specific tickets
- [x] #673 add a "Collection context" tab to all non-Collection component show pages
- [x] #673 remove the current static snapshot 
- [x] #673 display the collection tree in the new tab, open to the current component level
   - current component is highlighted
   - segments of the tree above the current component are collapsed and can be expanded by user action
- [x] #670 layout changes to the collection tree for desktop and mobile

**Comment by mejackreed** [comment]
All of these items have now been resolved.
