### ISSUE TITLE
Add a "Collection context" tab with interactive Collection navigation

### ISSUE THREAD

**Issue by jvine** [projectblacklight/arclight#673]
Part of #668, also related to #645.

Currently: 
- the Collection show page has a "Contents" tab that displays the collection tree
- other component show pages have a static "Collection context" snapshot on the "Overview" tab

Goal is to:
- create a new tab for "Collection context"
- within that tab, replace the static context snapshot with an interactive tree, open to the current component level

### Before
<img width="500" alt="context before" src="https://user-images.githubusercontent.com/6945691/63968431-88a3a380-ca54-11e9-9170-2c5d0ad3801c.png">

### After
<img width="500" alt="context after" src="https://user-images.githubusercontent.com/6945691/63968432-88a3a380-ca54-11e9-8930-489515df71fb.png">

## Tasks
**Note that all these changes affect non-Collection component pages only.** 
- [x] #810: Add a "Collection context" tab as the first item in the tablist. See #645 for placement 
- [x] Remove the static "Collection context" snapshot
- [x] #810: The Overview tab should now be empty, from changes in #628 and removal of the snapshot, so it can be removed
- [x] **Display the collection tree in the "Collection context" tab**
   - Layout of the tree is as spec'd in #670 
   - Tree is open to show the current component
   - #811: Current component is highlighted with a yellow background (1, below)
   - #811: Because the current component may be far down in the tree, portions of the tree are hidden to ensure the current component is visible in the tab. 
   - #812: One sibling _above_ the current component is displayed; any siblings above that are hidden, with an Expand button to mark the absence. (2)
   - #812: The immediate parent _above_ the current component is shown; the remainder of the tree to the top is hidden, with an expand button. (3)
   - #811:The entire remaining tree _below_ the current component is shown. All siblings of the component (4), siblings of the parent (5), and all remaining series & subseries (6). All components are closed if they are not required to be open to display the current component.
- [x] #813: **Open collapsed sections by clicking Expand** 
   - When the user clicks an Expand button, insert the hidden portion of the tree into that space, and remove the Expand button (there's no parallel Collapse behaviour). Expand (2) inserts all the siblings above the current one. Expand (3) inserts the remainder of the tree above the immediate parent. [Interactive mockup of this behaviour](https://xd.adobe.com/view/fe3abb57-312c-4393-6031-b3da9dba7023-880b/).

<img width="1123" alt="current componetnt in tree" src="https://user-images.githubusercontent.com/6945691/63970094-29479280-ca58-11e9-96d0-adbffe79733b.png">

**Comment by mejackreed** [comment]
Resolved in previous work, finalized in #957
