### ISSUE TITLE
Update display and behaviour of "Online content"

### ISSUE THREAD

**Issue by jvine** [projectblacklight/arclight#678]
This ticket (and the design) makes a distinction between components that have children (direct or indirect) with online content, and components that have direct online content. 

Currently, online content for a component is shown:
- At the Collection level, children with online content are shown as a search result in the "Online content" tab. Only the first 10 results are shown. 
- At the component level, on the show page of a component that has a `<dao>`, as links in the "Online content" tab. 
- Any layers between the collection and the online item show "No online content".

## Revised design
On component pages:
- children with online content are presented as a search result in the "Online content" tab
- direct online content is presented "above the tabs" 
- a component can have both direct content AND children with online content. ([Example](https://arclight-demo.projectblacklight.org/catalog/aoa271)). This is not supported in the current structure. 

### Tasks
- [ ] #680 Show online content at every level of the hierarchy.
- [ ] #679 Show children with online content as a search result with pagination.
- [ ] #680 Display the links/viewer/etc. for online items "above the tabs" with the item metadata.

### Online content in collection tree
<img width="1016" alt="online content in tree" src="https://user-images.githubusercontent.com/6945691/63985912-95d98600-ca86-11e9-8d3b-64eba91fd14f.png">

### Component with online children (no direct content)
<img width="1010" alt="online children" src="https://user-images.githubusercontent.com/6945691/63986249-fa491500-ca87-11e9-9fcd-e06764f64bc9.png">

### Component with direct online content (no children)
<img width="1136" alt="direct online content" src="https://user-images.githubusercontent.com/6945691/63986079-3c258b80-ca87-11e9-82bb-9b98645324a2.png">

**Comment by seanaery** [comment]
Resolving this issue as part of a review of `arclight 1.0.x`. The 1.x layout diverges enough from 0.x that these mockups no longer apply.
