### ISSUE TITLE
Add a list view for grouped search results

### ISSUE THREAD

**Issue by ggeisler** [projectblacklight/arclight#681]
Part of #667. Some aspects of this assume that #669 has been completed.

We don't have a current implementation of grouping search results by collection, so this is a new feature. When the user selects the "Group by collection" option added in #676, we switch to a new view of the results for the current query. Which I think means running a new Solr query using the current search parameters and adding appropriate `grouping` parameters, including a `group.limit` value of `3` so we show up to three result items per group. The rest of this ticket describes what we'd like to do for collection grouping from a UX perspective, but we might need to discuss the Solr/Blacklight details with @mejackreed or @jkeck (and/or others who have Solr grouping knowledge), if it seems like there are technical hurdles to this design.

<img width="635" alt="Screen Shot 2019-08-29 at 4 20 50 PM" src="https://user-images.githubusercontent.com/101482/64035840-9b76b080-cb06-11e9-8ef7-bab5fa7ae551.png">

 **A: Update the result count message.** Since the user is interested in seeing results via collections, the message should reflect the number of **collections** returned by the query, instead of documents (the number of docs per collection is covered in F). Showing 10 collections per page, each with several docs, does seem like it will create a large page (vertically and page-load wise), but we have the per-page dropdown to consider, and we're not sure how easily we can operate with two per page approaches in the same app.

- [x] Display a result count message in the format "1 - x of y collections" where x uses the per-page parameter (based on the number of groups/collections) and y is the total number of groups/collections returned by the grouped query.

**B: Collection info box** - The box contains all the collection-related elements to display for each group of results.

- [x] Add shaded box around collection elements. Use the styling currently used for the header portion of the current search result items (CSS class `al-document-title-bar`), except don't include a border.

**C: Repository breadcrumb.** 

- [x] Display a breadcrumb using the same styling we're using for the breadcrumb elsewhere
- [x] Include only the collection's owning repository
- [x] Link the breadcrumb to the repository show page

**D: Collection title and extent.** 

- [x] Display the collection title using an `<h3 />` element, but do not link it.
- [x] Display the extent of the collection (if it exists) on the same line as the collection title, styled as a Bootstrap badge, with a white background and `#CED4DA` border color (we can revisit styling details after seeing the implementation).

**E: Collection abstract.** 

- [x] Display the collection abstract (use the collection scope note if an abstract doesn't exist for the collection), truncated as necessary to three lines, showing the "view more" collapse/expand toggle if truncated. 
- [x] Add a max-width of 45em to the abstract/scope note.

**F: Collection result message** - There are two parts to this, unless the collection group has 3 or fewer document matches, in which case only the first part is needed.

- [x] Show the result message for the collection below the collection box. Indent by ~15px
- [x] The first part of the message is a static string that says `Top 3 results`
- [x] The second part of the message is a link in the form of "view all x" where x is the number of documents matched in that collection (I think this is the `numFound` value in the Solr grouped response, but don't trust me). Selecting the link should take the user to the normal, ungrouped results for the current query, **with that collection added as a constraint**.
- [x] If a collection returns 3 or fewer documents, change the first, static string to `x results` (where x is the count for the collection) and omit the second, linked part.

**G: Result items.** The display of the first three result items is very similar to what is specified in #669. The breadcrumb is the only thing that is different:

- [x] Indent the result items to be left-aligned with the "Top 3 results" string above
- [x] Omit the repository and collection from the result item breadcrumb. 
- [x] Use the appropriate component level icon (TBD) for the first item in the breadcrumb

## Mobile adjustments
There are no special adjustments needed for the mobile view of grouped search results (that I can think of now, anyway), other than following the same adjustment to the search result items that was described in the "Adjustments for mobile" section of #669: the bookmark checkbox, online content badge, and container label should move to display below the item breadcrumb. Here's an example of how things should look on mobile:

<img width="323" alt="Screen Shot 2019-08-30 at 9 09 56 AM" src="https://user-images.githubusercontent.com/101482/64035783-7bdf8800-cb06-11e9-8cc6-693e37c2cfe6.png">

**Comment by mejackreed** [comment]
Lingering issue split out to #899
