### ISSUE TITLE
Updates to Search bar - story ticket

### ISSUE THREAD

**Issue by jvine** [projectblacklight/arclight#716]
Overall plan for the search bar includes several pieces. Goals are to replace and improve the "search within this collection" functionality previously removed from the sidebar, and provide a framework for adding integrated digital content search to ArcLight. 

- [ ] 1. add a dropdown to the search bar that allows the user to scope their search to the current collection, or all collections
- [ ] 2. adjust the content of the Fields dropdown to match the current scope
- [ ] 3. remove collapse behaviour from search bar on mobile
- [ ] 4. add a "digital content" option to the dropdown. Interaction details are straightforward; indexing details TBD.

<img width="985" alt="search bar" src="https://user-images.githubusercontent.com/6945691/64291834-e84ef280-cf1d-11e9-8175-6d1a9b7810a6.png">
<img width="395" alt="search bar mobile" src="https://user-images.githubusercontent.com/6945691/64291884-061c5780-cf1e-11e9-9d60-4e67f20a9f81.png">
